#!/usr/bin/env python3
"""PREDICTION-SIDE Elo snapshot - parsed 2026-07-12 from World.tsv.

Auto-generated by fetch_elo_current.py. Do NOT import from backtests
(two-ledger governance: backtests use worldcup_2026_data_ko.py).
"""

ELO_CURRENT = {
    "Algeria": 1756,
    "Argentina": 2156,
    "Australia": 1795,
    "Austria": 1821,
    "Belgium": 1948,
    "Bosnia": 1605,
    "Brazil": 1993,
    "Cabo Verde": 1619,
    "Canada": 1729,
    "Colombia": 2003,
    "Cote dIvoire": 1727,
    "Croatia": 1881,
    "Czechia": 1680,
    "DR Congo": 1704,
    "Ecuador": 1871,
    "Egypt": 1742,
    "England": 2076,
    "France": 2163,
    "Germany": 1908,
    "Ghana": 1570,
    "Haiti": 1517,
    "Iran": 1764,
    "Iraq": 1561,
    "Japan": 1888,
    "Jordan": 1628,
    "Korea": 1723,
    "Mexico": 1913,
    "Morocco": 1901,
    "Netherlands": 1971,
    "New Zealand": 1534,
    "Norway": 1972,
    "Panama": 1658,
    "Paraguay": 1814,
    "Portugal": 1995,
    "Qatar": 1411,
    "Saudi Arabia": 1596,
    "Senegal": 1816,
    "Spain": 2190,
    "Sweden": 1731,
    "Switzerland": 1949,
    "Tunisia": 1562,
    "Turkiye": 1852,
    "USA": 1747,
    "Uruguay": 1841,
    "Uzbekistan": 1631,
}

FETCHED_AT_UTC = "2026-07-12T07:08:30Z"
SOURCE = "https://www.eloratings.net/World.tsv"
SOURCE_SHA256 = "4590985250059fbdaaca7aff8d5322ded98815c8a33da17add5e9b60bd7d7326"
ESTIMATES = []

# Legacy date-only fields retained for older prediction scripts.
FETCHED = "2026-07-12"
FETCHED_BASE = "2026-07-12"
