#!/usr/bin/env python3
"""Parse retained World.tsv bytes into a prediction-side ELO_CURRENT dict.

Network capture happens in ``capture_elo_evidence.py``. For current runs, pass
its receipt so the response time and raw-byte binding cannot be caller-stamped:

    python3 fetch_elo_current.py --tsv world_YYYY-MM-DD.tsv \
        --receipt world_YYYY-MM-DD.receipt.json \
        --out elo_current_YYYYMMDD.py

TSV format (observed 2026-07-04): tab-separated, one team per line;
col 1/2 = rank, col 3 = eloratings 2-letter code, col 4 = CURRENT rating.
Governance: output is PREDICTION-SIDE ONLY. Backtests keep the historical
snapshot in `worldcup_2026_data_ko.py` (two-ledger separation, report 7/4 #2a).
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
from pathlib import Path
import tempfile

from elo_snapshot import (
    CODE_TO_TEAM,
    EloCaptureReceipt,
    EloSnapshotError,
    OFFICIAL_ELO_SOURCE,
    UNVERIFIED_REPLAY_METHOD,
    load_elo_capture_receipt,
    parse_world_tsv_bytes,
)


def _fetched_at_utc(raw: str | None) -> _dt.datetime:
    if raw is None:
        raise ValueError(
            "--fetched-at-utc is required for a saved --tsv; "
            "the parse time is not the download time"
        )
    text = raw.strip().replace("Z", "+00:00")
    try:
        value = _dt.datetime.fromisoformat(text)
    except ValueError as exc:
        raise ValueError(f"invalid --fetched-at-utc: {raw!r}") from exc
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError("--fetched-at-utc must include a timezone offset")
    return value.astimezone(_dt.timezone.utc)


def emit_module(
    elo: dict[str, int],
    out_path: str | Path,
    *,
    source_bytes: bytes,
    fetched_at_utc: _dt.datetime,
    capture_receipt: EloCaptureReceipt | None,
) -> None:
    fetched_at = fetched_at_utc
    if fetched_at.tzinfo is None or fetched_at.utcoffset() is None:
        raise ValueError("fetched_at_utc must include a timezone offset")
    fetched_at = fetched_at.astimezone(_dt.timezone.utc)
    fetched_text = fetched_at.isoformat(timespec="seconds").replace("+00:00", "Z")
    today = fetched_at.date().isoformat()
    if not isinstance(source_bytes, bytes):
        raise ValueError("source_bytes must be bytes")
    source_sha256 = hashlib.sha256(source_bytes).hexdigest()
    receipt_sha256 = capture_receipt.receipt_sha256 if capture_receipt is not None else None
    capture_method = (
        capture_receipt.capture_method
        if capture_receipt is not None
        else UNVERIFIED_REPLAY_METHOD
    )
    lines = [
        '#!/usr/bin/env python3',
        f'"""PREDICTION-SIDE Elo snapshot - parsed {today} from World.tsv.',
        '',
        'Auto-generated by fetch_elo_current.py. Do NOT import from backtests',
        '(two-ledger governance: backtests use worldcup_2026_data_ko.py).',
        '"""',
        '',
        'ELO_CURRENT = {',
    ]
    for team, r in sorted(elo.items()):
        lines.append(f'    "{team}": {r},')
    lines += [
        '}',
        '',
        f'FETCHED_AT_UTC = "{fetched_text}"',
        f'SOURCE = "{OFFICIAL_ELO_SOURCE}"',
        f'SOURCE_SHA256 = "{source_sha256}"',
        f"SOURCE_RECEIPT_SHA256 = {receipt_sha256!r}",
        f'CAPTURE_METHOD = "{capture_method}"',
        f"SOURCE_BYTE_COUNT = {len(source_bytes)}",
        'ESTIMATES = []',
        '',
        '# Legacy date-only fields retained for older prediction scripts.',
        f'FETCHED = "{today}"',
        f'FETCHED_BASE = "{today}"',
        '',
    ]
    output = Path(out_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=output.parent,
        prefix=f".{output.name}.",
        suffix=".tmp",
        delete=False,
    ) as fh:
        temp_path = Path(fh.name)
        fh.write("\n".join(lines))
    temp_path.replace(output)
    print(f"wrote {out_path}: {len(elo)} teams")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--tsv", required=True, help="saved World.tsv path")
    ap.add_argument(
        "--out",
        default="elo_current_latest.py",
        help="output .py module path (default: elo_current_latest.py)",
    )
    ap.add_argument(
        "--required-team",
        action="append",
        default=[],
        help="team that must be present; repeat for every scheduled fixture team",
    )
    ap.add_argument(
        "--receipt",
        help="direct HTTP capture receipt from capture_elo_evidence.py",
    )
    ap.add_argument(
        "--fetched-at-utc",
        help="legacy replay timestamp; requires --allow-unverified-replay",
    )
    ap.add_argument(
        "--allow-unverified-replay",
        action="store_true",
        help="allow a non-official historical/replay module without a capture receipt",
    )
    a = ap.parse_args()
    if a.receipt and a.fetched_at_utc:
        ap.error("--receipt and --fetched-at-utc are mutually exclusive")
    if a.receipt and a.allow_unverified_replay:
        ap.error("--allow-unverified-replay cannot be used with --receipt")
    if not a.receipt and not a.allow_unverified_replay:
        ap.error(
            "--receipt is required; historical replay must explicitly pass "
            "--allow-unverified-replay with --fetched-at-utc"
        )
    if a.allow_unverified_replay and not a.fetched_at_utc:
        ap.error("--allow-unverified-replay requires --fetched-at-utc")
    source_path = Path(a.tsv)
    try:
        source_bytes = source_path.read_bytes()
    except OSError as exc:
        ap.error(f"cannot read World.tsv {source_path}: {exc}")
    try:
        elo = parse_world_tsv_bytes(source_bytes, source_path)
    except EloSnapshotError as exc:
        ap.error(str(exc))
    if len(elo) < 16:
        raise SystemExit(f"parsed only {len(elo)} teams - check TSV format")
    missing = list(dict.fromkeys(team for team in a.required_team if team not in elo))
    if missing:
        raise SystemExit(f"required team(s) missing from World.tsv: {', '.join(missing)}")
    receipt = None
    if a.receipt:
        try:
            receipt = load_elo_capture_receipt(
                a.receipt,
                source_tsv=source_path,
                source_bytes=source_bytes,
            )
        except EloSnapshotError as exc:
            ap.error(str(exc))
        fetched_at = receipt.response_completed_at_utc
    else:
        try:
            fetched_at = _fetched_at_utc(a.fetched_at_utc)
        except ValueError as exc:
            ap.error(str(exc))
    emit_module(
        elo,
        a.out,
        source_bytes=source_bytes,
        fetched_at_utc=fetched_at,
        capture_receipt=receipt,
    )
