#!/usr/bin/env python3
"""Parse a saved eloratings.net World.tsv into a prediction-side ELO_CURRENT dict.

NO NETWORK CODE ON PURPOSE — fetching happens via the assistant's web_fetch
tool (verified working on https://www.eloratings.net/World.tsv, 2026-07-04);
save its output to a file and run:

    python3 fetch_elo_current.py --tsv world_YYYY-MM-DD.tsv \
        --out elo_current_YYYYMMDD.py

TSV format (observed 2026-07-04): tab-separated, one team per line;
col 1/2 = rank, col 3 = eloratings 2-letter code, col 4 = CURRENT rating.
Governance: output is PREDICTION-SIDE ONLY. Backtests keep the historical
snapshot in `worldcup_2026_data_ko.py` (two-ledger separation, report 7/4 #2a).
"""
from __future__ import annotations

import argparse
import datetime as _dt

# eloratings code -> our dataset team name. Only codes cross-verified against
# known ratings are mapped (2026-07-04 audit); extend cautiously.
CODE_TO_TEAM = {
    "ES": "Spain", "AR": "Argentina", "FR": "France", "EN": "England",
    "BR": "Brazil", "PT": "Portugal", "CO": "Colombia", "NL": "Netherlands",
    "MX": "Mexico", "CH": "Switzerland", "NO": "Norway", "BE": "Belgium",
    "DE": "Germany", "JP": "Japan", "MA": "Morocco", "HR": "Croatia",
    "EC": "Ecuador", "TR": "Turkiye", "UY": "Uruguay", "PY": "Paraguay",
    "AT": "Austria", "SN": "Senegal", "AU": "Australia", "US": "USA",
    "EG": "Egypt", "CA": "Canada", "DZ": "Algeria", "GH": "Ghana",
    "CV": "Cabo Verde", "CI": "Cote dIvoire", "KR": "Korea", "SE": "Sweden",
    "CZ": "Czechia", "PA": "Panama", "JO": "Jordan", "UZ": "Uzbekistan",
    "CD": "DR Congo", "IR": "Iran", "IQ": "Iraq", "TN": "Tunisia",
    "HT": "Haiti", "SA": "Saudi Arabia", "NZ": "New Zealand", "QA": "Qatar",
    "BA": "Bosnia",
    # NOT mapped (code unverified): Scotland — add after checking eloratings code.
}


def parse_world_tsv(path: str) -> dict[str, int]:
    out: dict[str, int] = {}
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 4:
                continue
            code, rating = parts[2].strip(), parts[3].strip()
            team = CODE_TO_TEAM.get(code)
            if team is None:
                continue
            try:
                out[team] = int(rating)
            except ValueError:
                continue
    return out


def emit_module(elo: dict[str, int], out_path: str, tsv_path: str) -> None:
    today = _dt.date.today().isoformat()
    lines = [
        '#!/usr/bin/env python3',
        f'"""PREDICTION-SIDE Elo snapshot — parsed {today} from {tsv_path}.',
        '',
        'Auto-generated by fetch_elo_current.py. Do NOT import from backtests',
        '(two-ledger governance: backtests use worldcup_2026_data_ko.py).',
        '"""',
        '',
        'ELO_CURRENT = {',
    ]
    for team, r in sorted(elo.items()):
        lines.append(f'    "{team}": {r},')
    lines += ['}', '', f'FETCHED = "{today}"',
              'SOURCE = "https://www.eloratings.net/World.tsv"', '']
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {out_path}: {len(elo)} teams")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--tsv", required=True, help="saved World.tsv path")
    ap.add_argument("--out", required=True, help="output .py module path")
    a = ap.parse_args()
    elo = parse_world_tsv(a.tsv)
    if len(elo) < 16:
        raise SystemExit(f"parsed only {len(elo)} teams — check TSV format")
    emit_module(elo, a.out, a.tsv)
