#!/usr/bin/env python3
"""PREDICTION-SIDE Elo snapshot - parsed 2026-07-15 from World.tsv.

Auto-generated by fetch_elo_current.py. Do NOT import from backtests
(two-ledger governance: backtests use worldcup_2026_data_ko.py).
"""

ELO_CURRENT = {
    "Algeria": 1756,
    "Argentina": 2177,
    "Australia": 1795,
    "Austria": 1821,
    "Belgium": 1948,
    "Bosnia": 1605,
    "Brazil": 1993,
    "Cabo Verde": 1619,
    "Canada": 1729,
    "Colombia": 2003,
    "Cote dIvoire": 1727,
    "Croatia": 1882,
    "Czechia": 1680,
    "DR Congo": 1704,
    "Ecuador": 1871,
    "Egypt": 1742,
    "England": 2097,
    "France": 2121,
    "Germany": 1908,
    "Ghana": 1570,
    "Haiti": 1517,
    "Iran": 1764,
    "Iraq": 1561,
    "Japan": 1888,
    "Jordan": 1628,
    "Korea": 1723,
    "Mexico": 1913,
    "Morocco": 1901,
    "Netherlands": 1971,
    "New Zealand": 1534,
    "Norway": 1951,
    "Panama": 1658,
    "Paraguay": 1814,
    "Portugal": 1995,
    "Qatar": 1411,
    "Saudi Arabia": 1596,
    "Senegal": 1816,
    "Spain": 2232,
    "Sweden": 1731,
    "Switzerland": 1928,
    "Tunisia": 1562,
    "Turkiye": 1852,
    "USA": 1747,
    "Uruguay": 1841,
    "Uzbekistan": 1631,
}

FETCHED_AT_UTC = "2026-07-15T17:24:03Z"
SOURCE = "https://www.eloratings.net/World.tsv"
SOURCE_SHA256 = "b947c3c3f033a2708500efd6207beb2db247dc747df93e4b7381cce6ddea43cb"
SOURCE_RECEIPT_SHA256 = '7bb15442eb9e3e707f3d3cdbec4ec4faf766d4704b46b7919b38c6a1e3521d1e'
CAPTURE_METHOD = "direct_http_response_body"
SOURCE_BYTE_COUNT = 30333
ESTIMATES = []

# Legacy date-only fields retained for older prediction scripts.
FETCHED = "2026-07-15"
FETCHED_BASE = "2026-07-15"
